name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]   # 32位 和 64位
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: |
          pip install pyinstaller pydivert pycryptodome psutil

      - name: Build exe
        run: |
          pyinstaller --onefile main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tlsfragment-${{ matrix.arch }}
          path: dist/*
