name: Build TlsFragment Client (Aardio)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86, x64]   # 同时构建 32 位 / 64 位

    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ 下载 Aardio 官方压缩包
      - name: Download Aardio
        run: |
          Invoke-WebRequest -Uri "https://d.aardio.com/ide/aardio.7z" -OutFile "aardio.7z"

      # 3️⃣ 解压 7z 文件
      - name: Extract Aardio
        run: |
          7z x aardio.7z -oaardio
          Write-Output "Aardio files:"
          Get-ChildItem -Recurse aardio

      # 4️⃣ 显示项目目录（调试）
      - name: Show project folder
        run: |
          Write-Output "Project directory content:"
          Get-ChildItem -Recurse

      # 5️⃣ 构建 Aardio 工程
      - name: Build Client
        run: |
          Write-Output "Building $($env:MATRIX_ARCH) version..."
          .\aardio\aardio.exe /build py/run.aproj

      # 6️⃣ 自动查找生成的 exe
      - name: Find generated exe
        id: find_exe
        run: |
          $exe = Get-ChildItem -Path . -Filter *.exe -Recurse | Where-Object { $_.FullName -notmatch "aardio" } | Select-Object -First 1
          if (-not $exe) { Write-Error "No exe found!"; exit 1 }
          Write-Output "Found exe: $($exe.FullName)"
          echo "EXE_PATH=$($exe.FullName)" >> $env:GITHUB_ENV

      # 7️⃣ 上传构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TlsFragment-Client-${{ matrix.arch }}
          path: ${{ env.EXE_PATH }}
