name: Build TlsFragment Client (Aardio)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86, x64]   # 构建 32/64 位

    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ 安装依赖（如果有 Python 或其他工具，可在这里安装）
      - name: Setup dependencies
        run: |
          echo "No extra dependencies needed for aardio build"

      # 3️⃣ 显示目录（调试）
      - name: Show files
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          dir

      # 4️⃣ 编译客户端
      - name: Build Client
        run: |
          echo "Building ${{ matrix.arch }} version..."
          # 假设你的工程在仓库根目录 py/run.aproj
          # 构建不同位数需要修改工程配置或使用 aardio 命令行参数
          .\aardio\aardio.exe /build py/run.aproj
          
      # 5️⃣ 上传构建结果
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TlsFragment-Client-${{ matrix.arch }}
          path: bin\*.exe
