name: Build Windows EXE

on:
  workflow_dispatch:   # 手动触发构建

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86, x64]   # 同时打包 32 位 / 64 位

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: |
          pip install pyinstaller pydivert pycryptodome psutil

      - name: Show files (debug)
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          dir

      - name: Build exe
        run: |
          pyinstaller --onefile py/run.py --name TlsFragment-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TlsFragment-${{ matrix.arch }}
          path: dist/TlsFragment-${{ matrix.arch }}.exe
