name: Build TlsFragment Client (Aardio)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Aardio
        run: |
          curl -L -o aardio.7z https://d.aardio.com/ide/aardio.7z

      - name: Extract Aardio
        run: |
          7z x aardio.7z -oaardio

      - name: Build Client
        run: |
          echo "Building ${{ matrix.arch }} version..."
          .\aardio\aardio.exe /build py/run.aproj

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TlsFragment-Client-${{ matrix.arch }}
          path: bin\*.exe
